# Generated by Django 5.2.6 on 2025-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('main_pokemon', models.CharField(max_length=25)),
            ],
        ),
    ]
