# Generated by Django 5.2.6 on 2025-09-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_treinador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treinador',
            old_name='nome',
            new_name='nomeT',
        ),
    ]
