# Generated by Django 5.2.6 on 2025-09-19 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nome_treinador_nomet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='treinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.treinador'),
        ),
    ]
