# Generated by Django 5.2.6 on 2025-09-19 03:41

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pokemon_treinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='treinador',
            field=models.ForeignKey(default=app.models.get_default_treinador, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.treinador'),
        ),
    ]
